apiVersion: v2
appVersion: "0.14.4"
description: Carthago Operator for Jenkins
name: carthago-op-jenkins
version: 0.4.0
icon: https://raw.githubusercontent.com/carthago-cloud/carthago-op-jenkins-helm/master/assets/jenkins-operator-icon.png
