# Carthago Operator for Jenkins Helm chart

# apiVersion is the version of the Custom Resources manifests
apiVersion: carthago.cloud/v1beta1

# operator is section for configuring operator deployment
operator:

  replicaCount: 1

  # image is the name (and tag) of the Carthago Operator for Jenkins image
  image: carthago.azurecr.io/carthago-op-jenkins:0.13.0

  # imagePullPolicy defines policy for pulling images
  imagePullPolicy: IfNotPresent

  # imagePullSecrets is used to pull images from private repository
  imagePullSecrets:
    - name: token

  # command
  command:
    - /manager

  # args is used to specify flags
  args:
    - --leader-elect=true

  # nameOverride overrides the app name
  nameOverride: ""

  # fullnameOverride overrides the deployment name
  fullnameOverride: ""

  # Resource limit/request for Carthago Operator
  # See https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ for details
  resources: {}

  # NodeSelector for Carthago Operator
  # For more details see https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
  nodeSelector: {}

  # Tolerations are applied to pods, and allow the pods to schedule onto nodes with matching taints.
  # See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more details
  tolerations: []

  # Affinity allows you to constrain which nodes your pod is eligible to be scheduled on, based on labels on the node.
  # For more details see https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  # JenkinsNamespace is used by Carthago Operator to watch namespace where Jenkins will be deployed
  jenkinsNamespace: "jenkins"

  # licenseSecretName specifies a name for the secret with license key. For paid plan features to be available,
  # a secret with this name containing valid information must be present in the same namespace as Carthago Operator
  # is deployed in.
  licenseSecretName: ""
