{{- if .Values.jenkinsSeedJobsEnabled }}
{{- $apiVersion := .Values.apiVersion }}
{{- range $jenkinsSeedJob := .Values.jenkinsSeedJobs}}
---
apiVersion: {{ $apiVersion }}
kind: JenkinsSeedJob
metadata:
  name: {{ $jenkinsSeedJob.name }}
  namespace: {{ $jenkinsSeedJob.namespace }}
  {{- with $jenkinsSeedJob.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $jenkinsSeedJob.description }}
  description: {{ $jenkinsSeedJob.description }}
  {{- end }}
  {{- with $jenkinsSeedJob.repository }}
  repository:  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $jenkinsSeedJob.triggers }}
  triggers:
    {{- if $jenkinsSeedJob.triggers.bitbucketTrigger.push }}
    bitbucketTrigger: {{ $jenkinsSeedJob.triggers.bitbucketTrigger.push }}
    {{- end }}
    {{- if $jenkinsSeedJob.triggers.bitbucketTrigger.push }}
    gitHubTrigger: {{ $jenkinsSeedJob.triggers.gitHubTrigger.push }}
    {{- end }}
    {{- if $jenkinsSeedJob.triggers.buildPeriodically }}
    buildPeriodically: {{ $jenkinsSeedJob.triggers.buildPeriodically }}
    {{- end }}
    {{- if $jenkinsSeedJob.triggers.pollSCM }}
    pollSCM: {{ $jenkinsSeedJob.triggers.pollSCM }}
    {{- end }}
  {{- end }}
  {{- with $jenkinsSeedJob.agentRef }}
  agentRef: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsSeedJob.settings }}
  settings:  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
