---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: service-account
---
{{- if ne .Values.operator.jenkinsNamespace .Release.Namespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
  namespace: {{.Values.operator.jenkinsNamespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: {{.Release.Namespace}}
{{- end }}