{{- if .Values.jenkinsConfigurationsAsCodeEnabled }}
  {{- $apiVersion := .Values.apiVersion }}
  {{- $jenkinsConfigurationAsCode := .Values.jenkinsConfigurationsAsCode}}
---
apiVersion: {{ $apiVersion }}
kind: JenkinsConfigurationAsCode
metadata:
  name: {{ $jenkinsConfigurationAsCode.name }}
  {{- with $jenkinsConfigurationAsCode.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsConfigurationAsCode.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $jenkinsConfigurationAsCode.data }}
  data: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsConfigurationAsCode.secretRef }}
  secretRef: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
