apiVersion: v2
appVersion: "0.12.1"
description: Custom Resources for Carthago Operator for Jenkins
name: carthago-op-jenkins-crs
version: 0.1.2
icon: https://raw.githubusercontent.com/carthago-cloud/carthago-op-jenkins-helm/master/assets/jenkins-operator-icon.png
